# Generated by Django 4.0.1 on 2023-02-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('preparing', 'PREPARING'), ('otw', 'OTW'), ('recieved', 'RECIEVED'), ('request_cancel', 'REQUEST CANCEL'), ('canceled', 'CANCELED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='shop.item'),
        ),
    ]
