# Generated by Django 4.0.1 on 2023-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinformation_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mycustomuser',
            managers=[
            ],
        ),
    ]
