# Generated by Django 4.0.1 on 2023-02-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
