# Generated by Django 4.0.1 on 2023-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('important', 'IMPORTANT'), ('common', 'COMMON'), ('broadcast', 'BROADCAST')], max_length=20),
        ),
    ]
