# Generated by Django 4.0.1 on 2023-02-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_notification_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
